//front-end
import Image from 'next/image'
//back-end

function LargeCard ({ img, title, description, buttonText }) {
  return (
    <div
      className='
        relative 
        py-16
        cursor-pointer
        '
    >
      <div
        className='
            relative
            h-96
            min-w-[300px]
            '
      >
        <Image
          src={img}
          layout='fill'
          objectFit='cover'
          className='rounded-2xl'
        />
      </div>
      <div
        className='
            absolute
            top-32
            left-12
            '
      >
        <h3
          className='
                text-4xl
                mb-3
                w-64
                text-gray-300
                '
        >
          {title}
        </h3>
        <p
          className='
                text-blue-200
                '
        >
          {description}
        </p>
        <button
          className='
                text-sm
                text-gray-700
                bg-gray-50
                px-4
                py-2
                rounded-lg
                font-semibold
                mt-5
                '
        >
          {buttonText}
        </button>
      </div>
    </div>
  )
}

export default LargeCard
