//front-end
import Head from 'next/head'
import Feed from '../components/feed/Feed'
import Sidebar from '../components/sidebar/Sidebar'
import Widgets from '../components/widgets/Widgets'
//back-end
import { auth, store } from '../firebase-file/firebaseFile'
import firebase from 'firebase'
import { useAuthState } from 'react-firebase-hooks/auth'

export default function Home ({ posts }) {
  return (
    <div className='h-screen overflow-hidden bg-gray-900'>
      <Head>
        <title>Twitter-counterpart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex '>
        {/**Sidebar */}
        <Sidebar />
        {/**Feed */}
        <Feed />
        {/**Widgets */}
        <Widgets posts={posts} />
      </main>
    </div>
  )
}

export async function serverSideProps (context) {
  const ref = store.collection('posts').doc(context.query.id)
  /**Pull posts from firebase */
  const postRes = await ref
    .collection('posts')
    .orderBy('timestamp', 'asc')
    .get()

  const posts = postRes.docs
    .map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
    .map(posts => ({
      ...posts,
      timestamp: posts.timestamp.toDate().getTime()
    }))

  return {
    props: {
      posts: JSON.stringify(posts)
    }
  }
}
